name: Laravel Package Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  misspell-linter:
    name: Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"

  phpcs-linter:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the workspace
        uses: actions/checkout@v2
      - uses: hrysd/action-php_codesniffer@v1.0.0
        with:
          github_token: ${{ secrets.github_token }}
          standard: PSR1,PSR2,PSR12
          target_directory: src

  phpmd-linter:
    name: PHPMD
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the workspace
        uses: actions/checkout@v2
      - name: Run php check code with reviewdog
        uses: GeneaLabs/action-reviewdog-phpmd@0.1.5

  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        php: [7.3,7.4]
    name: PHP ${{ matrix.php }}
    steps:
    - uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache/files
        key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

    - name: Setup PHP ${{ matrix.php }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, pgsql, pdo_pgsql
        coverage: xdebug

    - uses: zhulik/redis-action@1.1.0
      with:
        redis version: '5'
        number of databases: 100

    - name: Remove Nova on a pull request
      if: github.event_name == 'pull_request'
      run: composer remove laravel/nova --no-update --no-interaction --dev

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: |
        composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_PASSWORD }}"
        composer install --dev --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: Run Tests without Nova
      if: github.event_name == 'pull_request'
      run: vendor/bin/phpunit --configuration phpunit.xml --testsuite Integration,Feature --coverage-text --coverage-clover ./coverage.xml

    - name: Run Tests with Nova
      if: github.event_name != 'pull_request'
      run: vendor/bin/phpunit --configuration phpunit.xml --testsuite Nova,Integration,Feature --coverage-text --coverage-clover ./coverage.xml

    - name: CodeCov Report
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml # optional
